### ISSUE TITLE
`require` from Browserify in v0.11.0 from NPM is broken

### ISSUE THREAD

**Issue by laustdeleuran** [liabru/matter-js#312]
Hi,

After the update to `v0.11.0`, installing from NPM is broken. I get a bunch of the following errors ([see semi-full log here](https://cl.ly/2x3Z131y183F)). 

    Error: Cannot find module '../core/Common' from '/Users/laustdeleuran/Sites/revelator-website/node_modules/matter-js/build'

The error seems to come from [line 46-52](https://github.com/liabru/matter-js/blob/master/build/matter.js#L46) in `/build/matter.js`. Those files are [not included in the NPM build](https://cl.ly/2C152A0M3s2z).

For now, I'm rolling back to `v0.11.0`.

**Comment by laustdeleuran** [comment]
Looking closer at the built file, the files are included (e.g. [`Vertices` on line 7654](https://github.com/liabru/matter-js/blob/master/build/matter.js#L7654)), but for some reason my Gulp / Babel build chokes on it. It works fine with `v0.10.0`.

**Comment by liabru** [comment]
Can't reproduce this when doing:

```
npm i matter-js --save
node
> require('matter-js')
{ name: 'matter-js',
  version: '0.11.0',
  uses: [],
  used: [],
  use: [Function],
  before: [Function],
  after: [Function],
...
```

Does this work for you? 

I suspect the issue might be to do with change 0cb1d83.
Basically I changed main from the source to a browserify built UMD module, which should work fine everywhere?
Does anybody know why this might cause issues?

**Comment by laustdeleuran** [comment]
@liabru Weird, I'm using Browserify (on ES6 with `import` syntax) myself, so not sure why it chokes on this. But still, I suspect you're right in where the error originates. I'm still getting the error even when I remove the `babelify` transform and use the `require` syntax. 

Requiring `matter-js` directly in the node command line works fine. Not sure what is going on. :/

**Comment by codeclown** [comment]
I bumped into this issue a few days ago as well, thought there was something wrong with my local setup. Ended up just loading from CDN for the time being.

Definitely only happens with Browserify, because for some reason Browserify tries to parse the require-calls in the built version that is specified as the main file for Matter.

Following the StackOverflow answer to [the issue at hand](https://github.com/substack/node-browserify/issues/374), this is relevant:

> The module you want to use should be built with the standalone option. That option is intended for creating a file that can be loaded by other module systems (including browserify itself, node.js, requirejs, etc.)

Should probably build the distributed file with `--standalone Matter`?

**Comment by liabru** [comment]
@codeclown it already is built [using standalone](https://github.com/liabru/matter-js/blob/master/Gulpfile.js#L104-L108). I'm guessing the issue comes when trying to bundle an already browserified module due to it parsing the `require` calls when it really shouldn't. It's probably why webpack uses `__webpack_require__` instead. So I'll look into switching I think.

**Comment by codeclown** [comment]
There is something fishy about this, because a package built with `standalone` should not cause issues like this. I don't have time to inspect if it's a bug in Browserify or an issue with how Matter is built right now, but will try to at some point.

**Comment by liabru** [comment]
From the [browserify docs](https://github.com/substack/node-browserify) regarding standalone:

>Note that in standalone mode the require() calls from the original source will still be around, which >may trip up AMD loaders scanning for require() calls. You can remove these calls with derequire:

>$ npm install -g derequire
>$ browserify main.js --standalone Foo | derequire > bundle.js

So looks like this is a known issue with browserify?

**Comment by codeclown** [comment]
Apparently so. Maybe `package.json` should not point to the compiled file?

```
  "main": "src/module/main.js"
```

**Comment by rfoligno** [comment]
Won't the solution listed in your comment solve the problem @liabru? Webpack is great, but if there's a fix already available, it seems like something that could wait.

**Comment by codeclown** [comment]
You could probably hook up [`derequire` to gulp](https://github.com/twada/gulp-derequire) so it would be taken care of, no?

If this is something you'd consider, I could also contribute a pull request.

**Comment by liabru** [comment]
> Apparently so. Maybe package.json should not point to the compiled file?

I decided it's better to point it at a file a browser can use too, as that's the primary target. This is what [lodash does](https://github.com/lodash/lodash/blob/master/package.json#L6) for example. Also, the build does some automated replacement stuff (e.g. versioning) that is crucial to the new plugin system, which will fail if `main` just points at the raw source.

> Won't the solution listed in your comment solve the problem @liabru? Webpack is great, but if there's a fix already available, it seems like something that could wait.

Exactly, the first thing I'll try is adding `derequire` to the build step.

**Comment by liabru** [comment]
I just pushed `0.11.1` which uses `derequire`, can you try it out and tell me if it's solved?

**Comment by codeclown** [comment]
Yes, errors are gone.
